### ISSUE TITLE
HTML file with .xxx extension

### ISSUE THREAD

**Issue by Jan2220** [skydive241/Regshot-Advanced#2]
Hi,

when outputting as HTML-File, Regshot creates the html file with .xxx extension.
just a forgot to change before release or is this supposed to happen? 
a .html file would be nicer, because no renaming is needed to be displayed right in the browser...

**Comment by skydive241** [comment]
Hi!

No, that's not right. If you copied the folder "templates" containing file "html.tpl", the tool produces files with the right extension  :

[$$SETUP$$]
Extension=.htm
NoVals=0
LogFSChanges=1
Logger=1
...

Grretings
Patrick

**Comment by Jan2220** [comment]
Hi,
yes. the Templates directory is there and the [$$SETUP$$] of the html.tpl looks right too. 
while writing this, i noticed the html template has UTF-8 coding with BOM, the other templates without BOM.
changed the coding to UTF-8 (without BOM) and now it works perfectly. 

thanks

Jan
